### ISSUE TITLE
event field appearing as null in Splunk

### ISSUE THREAD

**Issue by ShahBinoy** [brycied00d/fluent-plugin-splunk-http-eventcollector#21]
My current fluentd.conf

```
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

<match hqwebprod1.* >
  @type splunk-http-eventcollector
  server HEC SERVER
  protocol https
  verify false
  token MY_TOKEN
  index MY_INDEX
  check_index true
  source blahduh
  sourcetype MY_SOURCETYPE
  time_key time
  time_format localtime
  format raw
  buffer_type memory
  buffer_queue_limit 16
  buffer_chunk_limit 8m
  flush_interval 2s
</match>
```

The Dockerfile that built the fluentd image
```
FROM fluent/fluentd:v0.14-onbuild

RUN apk -Uuv add groff less python py-pip \
 && pip install awscli

RUN apk add --update --virtual .build-deps \
        sudo build-base ruby-dev \
 && sudo gem install \
        fluent-plugin-splunk-http-eventcollector \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /var/cache/apk/* \
           /home/fluent/.gem/ruby/2.3.0/cache/*.gem

```

I start the fluentd forwarder like 
```bash
docker run --rm --name fluentd -p 24224:24224  -v /fluentd-hec-forwarder:/fluentd/etc fluentd-hec-forwarder:latest
```

Fluentd docker log message sender sends message like this 
```bash
docker run --rm --name pyecho --log-driver=fluentd --log-opt tag="hqwebprod1.{{.ID}}" --log-opt fluentd-address=172.17.0.2:24224 python:alpine echo "{ 'event': 'Hello world from pyecho' }"
```

The logs that appear on Splunk are like
```json
{"time":1508385549,"source":"blahduh","sourcetype":"MY_SOURCE_TYPE","host":"","index":"entdev","event":null}
```

**Comment by tomasare** [comment]
I am facing the same problem. event field appears null on splunk side. 
Any update on this?

**Comment by tw-tmac** [comment]
I also had the same problem. It most likely has to do with a hidden config flag that is only visible in the test. add the following line in your matcher:

```
all_items true
```

**Comment by seslattery** [comment]
I ran into this too, fixed it by changing the splunk URI to `"#{@protocol}://#{@server}/services/collector/event"` .   Opened PR #24 to address.  Hope this helps.

**Comment by Jitsusama** [comment]
As an FYI for anyone coming across this later, `fluent-plugin-splunk-http-eventcollector` expects the message contents to be in a `message` key by default. If you don't supply a `message` key, then you'll want to set `all_items true` in your plugin configuration to see fields. At this time, the `message` key is not configurable.
